default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: leak_test
  host: 127.0.0.1
  port: 5433

development:
  <<: *default
  database: leak_test_development

test:
  <<: *default
  database: leak_test_test

production:
  <<: *default
  database: leak_test_production
  username: leak_test
  password:
